-- Insert sample announcements
INSERT INTO announcements (title, category, priority, content, status, created_by) VALUES
('Emergency Weather Advisory - Tropical Storm Juanito', 'emergency', 'high', 'Residents are advised to take necessary precautions as Tropical Storm Juanito approaches our region. Please stay indoors and monitor official weather updates.', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Annual Community Christmas Festival', 'event', 'medium', 'Join us for our annual Christmas Festival featuring local vendors, food stalls, and entertainment for the whole family.', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('New Waste Collection Schedule', 'notice', 'medium', 'Starting January 2025, our waste collection schedule will be adjusted to better serve all barangays. Please check the new schedule posted in your barangay halls.', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Mayor''s Monthly Address', 'update', 'low', 'Watch the Mayor''s latest monthly address discussing recent developments and upcoming projects in our municipality.', 'draft', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1));

-- Insert sample news articles
INSERT INTO news_articles (title, category, excerpt, content, media_type, status, created_by) VALUES
('BDRRM Planning Training Workshop', 'training', 'On June 25, 2024, the Municipal Disaster Risk Reduction and Management Office conducted an essential training session.', 'On June 25, 2024, the Municipal Disaster Risk Reduction and Management Office (MDRRMO) conducted an essential training session on Barangay Disaster Risk Reduction and Management Planning at Barangay Basicao Interior. The event was designed to equip local leaders with the knowledge and tools necessary to develop effective disaster preparedness plans at the barangay level.', 'image', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Successful Nationwide Simultaneous Earthquake Drill', 'event', 'The municipality participated in the 2nd quarter nationwide simultaneous earthquake drill with over 5,000 participants.', 'The municipality participated in the 2nd quarter nationwide simultaneous earthquake drill with over 5,000 participants from schools, offices, and communities. The drill was conducted to test the readiness and response capabilities of various sectors in the event of a major earthquake.', 'image', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('20 Volunteers Complete Water Rescue Training', 'training', 'On November 19, 2021, the rescue volunteers underwent intensive training in Basic Life Support and Water Search and Rescue.', 'On November 19, 2021, the rescue volunteers of Pio Duran underwent intensive training in Basic Life Support, survival skills, and Water Search and Rescue (WASAR). This program was designed to equip them with essential life-saving techniques, ensuring they could effectively respond to water-related emergencies and provide immediate assistance to those in distress.', 'video', 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1));

-- Insert sample events
INSERT INTO events_activities (title, category, description, event_date, event_time, location, organizer, max_participants, registration_required, status, created_by) VALUES
('Earthquake Preparedness Seminar', 'training', 'Learn essential earthquake preparedness techniques and safety protocols for your family and community.', '2025-01-15', '09:00:00', 'Municipal Hall Conference Room', 'MDRRMO Pio Duran', 50, true, 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Community Fire Drill', 'drill', 'Quarterly fire drill exercise for all barangays to practice evacuation procedures and fire safety protocols.', '2025-01-20', '14:00:00', 'Barangay Plaza', 'MDRRMO & BFP', 200, false, 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('First Aid Training Workshop', 'training', 'Basic first aid training for community volunteers and barangay officials.', '2025-01-25', '08:30:00', 'Health Center', 'MDRRMO & DOH', 30, true, 'published', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1));

-- Insert sample hotline numbers
INSERT INTO hotline_numbers (service_name, primary_number, secondary_number, description, category, is_24_7, status, created_by) VALUES
('MDRRMO Emergency', '911', '(052) 234-5678', 'Municipal Disaster Risk Reduction and Management Office emergency hotline', 'emergency', true, 'active', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Police Station', '117', '(052) 456-7890', 'Pio Duran Police Station emergency line', 'police', true, 'active', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Fire Department', '116', '(052) 789-0123', 'Bureau of Fire Protection Pio Duran', 'fire', true, 'active', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Rural Health Unit', '(052) 321-4567', NULL, 'Municipal Health Office and Rural Health Unit', 'medical', false, 'active', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1)),
('Municipal Hall', '(052) 654-3210', NULL, 'Municipal Government Office main line', 'government', false, 'active', (SELECT id FROM auth.users WHERE email LIKE '%@mdrrmo.gov.ph' LIMIT 1));
